
server:
  port: 8586
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: LoginService
          uri: http://localhost:9191
          predicates:
            - Path=/api/v1/login/**
        - id: RegisterService
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/register/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost