
server:
  port: 8088
spring:
  application:
    name: REGISTER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZon: http://localhost:8761/eureka
  instance:
    hostname: localhost
